[package]
name = "pixum"
version = "0.1.0"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
ahash = { version = "0.8.2", features = ["serde"] }
axum = { version = "0.6.1", features = ["http2"] }
bytes = { version = "1.3.0", features = ["serde"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
