services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - REDIS_HOST=pixumcache
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    networks:
      - cache
    depends_on:
      - redis
  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    networks:
      cache:
        aliases:
          - pixumcache

networks:
  cache:
