services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    networks:
      - cache
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.0.7-bullseye
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cache

networks:
  cache:
